# code to install packages in the docker file
install.packages("dplyr")
install.packages("lubridate")
install.packages("ReinforcementLearning")
install.packages("magrittr")
install.packages("plotly")
install.packages("openssl")
install.packages("rvest")
install.packages("qdap")
install.packages("stringr")
install.packages("twitteR")
install.packages("syuzhet")
install.packages("scales")
install.packages("reshape2")
install.packages("gapminder")
install.packages("plumber")
install.packages("DT")
install.packages("shinyjs")
install.packages("V8")
install.packages("h2o")
install.packages("lazytrade")
install.packages("translateR")
install.packages("golem")
install.packages("cranlogs")
install.packages("shinydashboard")
install.packages("covr")

